// autogenerated ui file by ittOS-ui-designer. dont modify manually please <3

/*
{
  "Img": [
    0,
    0,
    "images/cat.ibi"
  ]
},
{
  "Rect": [
    0,
    0,
    52,
    320,
    25897
  ]
},
{
  "Rect": [
    428,
    0,
    52,
    320,
    25897
  ]
},
{
  "Text": [
    0,
    0,
    "wahoo",
    "Font_16x26",
    65535
  ]
}
*/